### ISSUE TITLE
hub singularity image not accessible 

### ISSUE THREAD

**Issue by kristianunger** [IARCbioinfo/IARC-nf#1]
Hi there,

when executing

`singularity pull shub://IARCbioinfo/pipeline-nf:v2.2`

I get the error:

> FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://IARCbioinfo/pipeline-nf:v2.2: the requested manifest was not found in singularity hub

Can you please check?

Best

Kristian

**Comment by V-Catherine** [comment]
Hi Kristian,
"pipeline-nf" is not the name of an existing pipeline. It's a generic name that should be replaced by the name of the pipeline you want to use. 
For example: singularity pull shub://IARCbioinfo/RNAseq-nf:v2.4. 
I'll update the explanations to make it clearer.
Best,
Catherine

**Comment by kristianunger** [comment]
Dear Catherine,

many thanks - this helps. I should have spotted myself.

Best

Kristian

Am Mo., 1. Feb. 2021 um 14:10 Uhr schrieb V-Catherine <
notifications@github.com>:

**Comment by kristianunger** [comment]
Hi Catherine,

unfortunately this doesn't wok either.

`singularity pull shub://IARCbioinfo/RNAseq-nf:v2.4.`

returns the error: 

> FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://IARCbioinfo/RNAseq-nf:v2.4: 403 Forbidden

**Comment by V-Catherine** [comment]
Sorry I put a dot at the end of my sentence in the previous message but the command is : 
`singularity pull shub://IARCbioinfo/RNAseq-nf:v2.4`

**Comment by kristianunger** [comment]
Works now! merci beaucoup!

Am Mo., 1. Feb. 2021 um 16:27 Uhr schrieb V-Catherine <
notifications@github.com>:
